- name: Create an OSA Server
  hosts: localhost
  connection: local
  gather_facts: false
  user: root
  tasks:
    - name: Ensure no upgrade test instance is present
      nova_compute:
        name: "{{ login_username }}-{{ region_name }}-{{ item }}"
        state: absent
        login_username: "{{ login_username }}"
        login_password: "{{ login_password }}"
        login_tenant_name: "{{ login_tenant_name }}"
        auth_url: "{{ os_auth_url }}"
        region_name: "{{ region_name | capitalize }}"
        image_name: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
        flavor_ram: 8192
        flavor_include: Performance
        key_name: "{{ os_keyname }}"
      with_items:
        - "{{ instance_name }}"
      tags:
        - cleanup-server
    - name: Launch a test instance
      nova_compute:
        name: "{{ login_username }}-{{ region_name }}-{{ item }}"
        state: present
        login_username: "{{ login_username }}"
        login_password: "{{ login_password }}"
        login_tenant_name: "{{ login_tenant_name }}"
        auth_url: "{{ os_auth_url }}"
        region_name: "{{ region_name | capitalize }}"
        image_name: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
        flavor_ram: 8192
        flavor_include: Performance
        key_name: "{{ os_keyname }}"
      with_items:
        - "{{ instance_name }}"
      register: nova_hosts
      tags:
        - setup-hosts
        - setup
    - name: Load inventory
      add_host:
        hostname: "{{ item.info.name.split('-')[-1] }}"
        ansible_ssh_host: "{{ item.info.accessIPv4 }}"
        ansible_ssh_port: "22"
        groups: os_nodes
      with_items: nova_hosts.results
      tags:
        - setup-hosts
        - setup
    - name: Wait for ssh
      wait_for:
        port: 22
        host: "{{ item.info.accessIPv4 }}"
        search_regex: OpenSSH
        delay: 10
      with_items: nova_hosts.results
      tags:
        - setup-hosts
        - setup
  vars:
    instance_name: "{{ osa_instance_name | default('Nightly-Test') }}"
    login_username: "{{ os_username }}"
    login_password: "{{ os_password }}"
    login_tenant_name: "{{ os_tenant_name }}"
    region_name: "{{ os_region_name }}"


- name: Run upgrade
  hosts: os_nodes
  gather_facts: false
  user: root
  tasks:
    - name: Install base packages
      apt:
        name: "{{ item }}"
        update_cache: "yes"
        cache_valid_time: "3600"
      with_items:
        - git
      tags:
        - install-packages
    - name: Clone OSA into place
      git:
        repo: "{{ osa_repo }}"
        dest: /opt/openstack-ansible
        update: yes
        force: yes
        version: "{{ osa_branch_source }}"
      failed_when: false
      tags:
        - clone-repo
    - name: Drop new infra-template for container affinity
      template:
        src: "templates/infra_hosts.yml"
        dest: "/opt/openstack-ansible/etc/rpc_deploy/conf.d/infra_hosts.yml"
      tags:
        - infra-template
    - name: Run the initial build
      command: scripts/gate-check-commit.sh
      args:
        chdir: /opt/openstack-ansible
      environment:
        RUN_TEMPEST: no
        RUN_PLAYBOOKS: no
        DEPLOY_TEMPEST: no
        DEPLOY_LOGGING: no
        DEPLOY_RPC_SUPPORT: no
      tags:
        - run-install
    - name: Clone OSA into place
      git:
        repo: "{{ osa_repo }}"
        dest: /opt/openstack-ansible
        update: yes
        force: yes
        version: "{{ osa_branch_target }}"
      failed_when: false
      tags:
        - clone-repo
    - name: Run the upgrade
      shell: >
        echo YES | scripts/run-upgrade.sh
      args:
        chdir: /opt/openstack-ansible
      tags:
        - run-upgrade
    - name: Install tempest
      command: openstack-ansible os-tempest-install.yml
      args:
        chdir: /opt/openstack-ansible/playbooks
      tags:
        - install-tempest
    - name: Run tempest
      command: scripts/run-tempest.sh
      args:
        chdir: /opt/openstack-ansible
      register: run_tempest
      until: run_tempest|success
      retries: 2
      delay: 10
      tags:
        - run-tempest


- name: Destroy an OSA test Server
  hosts: localhost
  connection: local
  gather_facts: false
  user: root
  tasks:
    - name: destroy an instance
      nova_compute:
        name: "{{ login_username }}-{{ region_name }}-{{ item }}"
        state: absent
        login_username: "{{ login_username }}"
        login_password: "{{ login_password }}"
        login_tenant_name: "{{ login_tenant_name }}"
        auth_url: "{{ os_auth_url }}"
        region_name: "{{ region_name | capitalize }}"
        image_name: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
        flavor_ram: 8192
        flavor_include: Performance
        key_name: "{{ os_keyname }}"
      with_items:
        - "{{ instance_name }}"
      when: not save_instance | bool
      tags:
        - destroy-server
  vars:
    save_instance: "{{ osa_save_instance | default('false') }}"
    instance_name: "{{ osa_instance_name | default('Nightly-Test') }}"
    login_username: "{{ os_username }}"
    login_password: "{{ os_password }}"
    login_tenant_name: "{{ os_tenant_name }}"
    region_name: "{{ os_region_name }}"
