- name: Run upgrade
  hosts: os_nodes
  gather_facts: false
  user: root
  tasks:
    - name: Remove containers with no purpose
      shell: |
        for container in $(lxc-ls | grep -e kibana -e elastic -e logstash); do
          lxc-destroy -fn $container
        done
      tags:
        - container-remove
    - name: Clone OSA into place
      git:
        repo: "{{ osa_repo }}"
        dest: /opt/openstack-ansible
        update: yes
        force: yes
        version: "{{ osa_branch_target }}"
      failed_when: false
      tags:
        - clone-repo
    - name: checkout refspec
      shell: >
        git fetch {{ osa_repo }} {{ git_refspec }} && git checkout FETCH_HEAD
      args:
        chdir: /opt/openstack-ansible
      when: git_refspec != ''
      tags:
        - ref-spec
    - name: Run the upgrade
      shell: >
        echo YES | scripts/run-upgrade.sh
      args:
        chdir: /opt/openstack-ansible
      tags:
        - run-upgrade
    - name: Install tempest
      command: openstack-ansible os-tempest-install.yml
      args:
        chdir: /opt/openstack-ansible/playbooks
      tags:
        - install-tempest
  vars:
    git_refspec: "{{ osa_refspec | default('') }}"

