- name: Destroy an OSA test Server
  hosts: localhost
  connection: local
  gather_facts: false
  user: root
  tasks:
    - name: destroy an instance
      nova_compute:
        name: "OS-TestNode.{{ login_username }}.{{ region_name }}.{{ item }}"
        state: absent
        login_username: "{{ login_username }}"
        login_password: "{{ login_password }}"
        login_tenant_name: "{{ login_tenant_name }}"
        auth_url: "{{ os_auth_url }}"
        region_name: "{{ region_name | capitalize }}"
        image_name: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
        flavor_ram: 8192
        flavor_include: Performance
        key_name: "{{ os_keyname }}"
      with_items:
        - "{{ instance_names }}"
      when: not save_instance | bool
      failed_when: false
      no_log: True
      tags:
        - destroy-server
  vars:
    save_instance: "{{ osa_save_instance | default('false') }}"
    instance_names:
      - "{{ osa_instance_name }}"
    login_username: "{{ os_username }}"
    login_password: "{{ os_password }}"
    login_tenant_name: "{{ os_tenant_name }}"
    region_name: "{{ os_region_name }}"
